### ISSUE TITLE
Commands receiving NAK should throw

### ISSUE THREAD

**Issue by hallsbyra** [bytedreamer/OSDP.Net#98]
This would be a breaking change so I thought I throw it up here for discussion before starting to make any changes.

Today there is somewhat inconsistent behavior when receiving NAK responses:

1. Commands that return a reply (e.g. `IdReport`) don't handle NAK and instead will throw an exception when trying to parse the NAK as a valid response.
2. Commands that don't expect a reply (e.g. `ReaderLedControl`) will check for NAK reply and return true/false to indicate success.

The problems with this is:

1. Inconsistent behavior between different commands. Sometimes an exception is thrown, sometimes false is returned.
2. The exception thrown in case 1 is misleading, since it is just a byproduct of not handling NAK. E.g. instead of something informative like "NAK (0x06) Encrypted communication is required to process this command.", one receives something like "Invalid size for the data".
3. In case 2, the NAK error code is not propagated to the client, which only receives a true/false.

I propose that: 

1. all commands check the received response and throw an informative exception in case of NAK.
2. commands that today return a `Task<bool>` is changed to return only `Task`.

**Comment by bytedreamer** [comment]
The original idea was that the client would listen to the NakReplyReceived event for NAK responses. It became clear that this was not a good decision for certain commands. A response object was created for these commands that included a Nak property. 

I completely agree with proposal 1. I'm only hesitant with 2, since it causes a breaking change. Let me ponder 2 for a few more days. I wonder if there is a way we can transition to a unified method while keeping backward compatibility. Even deprecating those Task<bool> methods for a few releases would be acceptable.

**Comment by hallsbyra** [comment]
Sorry if I give you headaches! :)

Even today, the commands returning `Task<bool>` can throw (e.g. com problems), so clients must already have exception handling in place. Maybe it's not such a big deal to also get the NAK as an exception?

An alternative could be to use something like `ReturnReplyData<T>` everywhere. But that would also be a breaking change. And bad for other reasons. I think it would be cleaner to always return the expected reply from the command methods. Any errors (NAK, parse errors, com errors, etc) are thrown as exceptions.

**Comment by hallsbyra** [comment]
I'd also like to add that this is not something I'm in dire need of right now. It's more of a future enhancement request.
